// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateForMinutes(arg1:number):Promise<boolean>;

export function Deactivate():Promise<boolean>;

export function GetRemainingTime():Promise<number>;

export function GetStatus():Promise<boolean>;

export function HandleWindowBlur():Promise<void>;

export function IsLaunchAtStartup():Promise<boolean>;

export function OpenURL(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RestoreMenuPosition():Promise<void>;

export function SetLaunchAtStartup(arg1:boolean):Promise<boolean>;

export function SetOnExpire(arg1:any):Promise<void>;

export function Toggle():Promise<boolean>;
