// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateForMinutes(arg1) {
  return window['go']['main']['App']['ActivateForMinutes'](arg1);
}

export function Deactivate() {
  return window['go']['main']['App']['Deactivate']();
}

export function GetRemainingTime() {
  return window['go']['main']['App']['GetRemainingTime']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HandleWindowBlur() {
  return window['go']['main']['App']['HandleWindowBlur']();
}

export function IsLaunchAtStartup() {
  return window['go']['main']['App']['IsLaunchAtStartup']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RestoreMenuPosition() {
  return window['go']['main']['App']['RestoreMenuPosition']();
}

export function SetLaunchAtStartup(arg1) {
  return window['go']['main']['App']['SetLaunchAtStartup'](arg1);
}

export function SetOnExpire(arg1) {
  return window['go']['main']['App']['SetOnExpire'](arg1);
}

export function Toggle() {
  return window['go']['main']['App']['Toggle']();
}
