// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateForMinutes(arg1:number):Promise<boolean>;

export function Deactivate():Promise<boolean>;

export function GetRemainingTime():Promise<number>;

export function GetStatus():Promise<boolean>;

export function QuitApp():Promise<void>;

export function SetOnExpire(arg1:any):Promise<void>;

export function Toggle():Promise<boolean>;
