// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateForMinutes(arg1) {
  return window['go']['main']['App']['ActivateForMinutes'](arg1);
}

export function Deactivate() {
  return window['go']['main']['App']['Deactivate']();
}

export function GetRemainingTime() {
  return window['go']['main']['App']['GetRemainingTime']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetOnExpire(arg1) {
  return window['go']['main']['App']['SetOnExpire'](arg1);
}

export function Toggle() {
  return window['go']['main']['App']['Toggle']();
}
